name: Funny
on: workflow_dispatch
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: curl
      uses: enflo/curl-action@master
      with:
        curl: https://api.ipv4.party/claim?name=lio.cat
